# BudAI Production Environment Deployment Specification

environment: production
region: us-west-1

services:
  api-gateway:
    enabled: true
    resources:
      memory_mb: 1024
      cpu_millicores: 1000
      replicas: 2  # High availability
    environment_variables:
      LOG_LEVEL: INFO
      ENABLE_TRACING: "true"
    dependencies:
      - orchestrator
      - voice-realtime

  orchestrator:
    enabled: true
    resources:
      memory_mb: 1024
      cpu_millicores: 1000
      replicas: 2  # High availability
    environment_variables:
      LOG_LEVEL: INFO
      POLL_INTERVAL_SECONDS: "30"
      MAX_CONCURRENT_WORKFLOWS: "20"
    dependencies:
      - agent-summarizer
      - agent-followup
      - agent-communicator

  agent-summarizer:
    enabled: true
    resources:
      memory_mb: 1024
      cpu_millicores: 1000
      replicas: 3  # Scale for concurrent meetings
    environment_variables:
      LOG_LEVEL: INFO
      REASONING_EFFORT: medium
      MAX_RETRIES: "3"
      TIMEOUT_SECONDS: "300"

  agent-followup:
    enabled: true
    resources:
      memory_mb: 512
      cpu_millicores: 500
      replicas: 2
    environment_variables:
      LOG_LEVEL: INFO

  agent-communicator:
    enabled: true
    resources:
      memory_mb: 512
      cpu_millicores: 500
      replicas: 2
    environment_variables:
      LOG_LEVEL: INFO

  voice-realtime:
    enabled: true
    resources:
      memory_mb: 1024
      cpu_millicores: 1000
      replicas: 2
    environment_variables:
      LOG_LEVEL: INFO

  slack-integration:
    enabled: true
    resources:
      memory_mb: 512
      cpu_millicores: 500
      replicas: 2
    environment_variables:
      LOG_LEVEL: INFO

secrets:
  openai_api_key:
    source: railway-vault
    key: OPENAI_API_KEY
  slack_signing_secret:
    source: railway-vault
    key: SLACK_SIGNING_SECRET
  slack_bot_token:
    source: railway-vault
    key: SLACK_AUTHORIZATION
  google_calendar_credentials:
    source: railway-vault
    key: GOOGLE_CALENDAR_SERVICE_ACCOUNT
  gmail_credentials:
    source: railway-vault
    key: GMAIL_AUTHORIZATION

features:
  enable_metrics: true
  enable_tracing: true
  auto_rollback: true
  health_check_interval: 30
  enable_alerting: true
  enable_autoscaling: true

